/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as NotesIdImport } from './routes/notes/$id'
import { Route as NotesAddNewIndexImport } from './routes/notes/add-new/index'
import { Route as NotesEditIdImport } from './routes/notes/edit/$id'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotesIdRoute = NotesIdImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => rootRoute,
} as any)

const NotesAddNewIndexRoute = NotesAddNewIndexImport.update({
  id: '/notes/add-new/',
  path: '/notes/add-new/',
  getParentRoute: () => rootRoute,
} as any)

const NotesEditIdRoute = NotesEditIdImport.update({
  id: '/notes/edit/$id',
  path: '/notes/edit/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdImport
      parentRoute: typeof rootRoute
    }
    '/notes/edit/$id': {
      id: '/notes/edit/$id'
      path: '/notes/edit/$id'
      fullPath: '/notes/edit/$id'
      preLoaderRoute: typeof NotesEditIdImport
      parentRoute: typeof rootRoute
    }
    '/notes/add-new/': {
      id: '/notes/add-new/'
      path: '/notes/add-new'
      fullPath: '/notes/add-new'
      preLoaderRoute: typeof NotesAddNewIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes/$id': typeof NotesIdRoute
  '/notes/edit/$id': typeof NotesEditIdRoute
  '/notes/add-new': typeof NotesAddNewIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes/$id': typeof NotesIdRoute
  '/notes/edit/$id': typeof NotesEditIdRoute
  '/notes/add-new': typeof NotesAddNewIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/notes/$id': typeof NotesIdRoute
  '/notes/edit/$id': typeof NotesEditIdRoute
  '/notes/add-new/': typeof NotesAddNewIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/notes/$id' | '/notes/edit/$id' | '/notes/add-new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/notes/$id' | '/notes/edit/$id' | '/notes/add-new'
  id: '__root__' | '/' | '/notes/$id' | '/notes/edit/$id' | '/notes/add-new/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesIdRoute: typeof NotesIdRoute
  NotesEditIdRoute: typeof NotesEditIdRoute
  NotesAddNewIndexRoute: typeof NotesAddNewIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesIdRoute: NotesIdRoute,
  NotesEditIdRoute: NotesEditIdRoute,
  NotesAddNewIndexRoute: NotesAddNewIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/notes/$id",
        "/notes/edit/$id",
        "/notes/add-new/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/notes/$id": {
      "filePath": "notes/$id.tsx"
    },
    "/notes/edit/$id": {
      "filePath": "notes/edit/$id.tsx"
    },
    "/notes/add-new/": {
      "filePath": "notes/add-new/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
